export enum DriveMimeTypes {
  Audio = 'application/vnd.google-apps.audio',
  Doc = 'application/vnd.google-apps.document',
  Drawing = 'application/vnd.google-apps.drawing',
  File = 'application/vnd.google-apps.file',
  Folder = 'application/vnd.google-apps.folder',
  Form = 'application/vnd.google-apps.form',
  FusionTable = 'application/vnd.google-apps.fusiontable',
  Map = 'application/vnd.google-apps.map',
  Photo = 'application/vnd.google-apps.photo',
  Script = 'application/vnd.google-apps.script',
  Site = 'application/vnd.google-apps.site',
  Slide = 'application/vnd.google-apps.presentation',
  Spreadsheet = 'application/vnd.google-apps.spreadsheet',
  ThirdParty = 'application/vnd.google-apps.drive-sdk',
  Unknown = 'application/vnd.google-apps.unknown',
  Video = 'application/vnd.google-apps.video',
}
